# sudo: false
# FIXME: Java compiler dies with OOM if run in container
sudo: required
dist: trusty
language: java
jdk:
- oraclejdk8
python:
- "2.7"
addons:
  postgresql: 9.4
before_install:
- sh travis/before_install.sh
- export TERM=dumb
script:
- ./gradlew shadowJar check
- ./myriadeploy/launch_local_cluster > ./myria.log 2>&1 &
- sleep 60
- python ~/myria-web/appengine/myria_web_main.py > ./myria-web.log 2>&1 &
- sleep 60
- ./integration_tests.py
after_failure:
- cat ./myria.log
- cat ./myria-web.log
- find . -name '*.stderr' | xargs cat
after_success:
- ./gradlew jacocoTestReport coveralls
- flake8 ./integration_tests.py ./python/MyriaPythonWorker.py
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
# encrypted AWS credentials for travis-ci IAM user under myria account
env:
  global:
    - secure: "djjW9ThHbafN5TUFGQi+mFkc4uQ8w6pQuSIT3kLOT8u78LuKSJ2LeO3kpqHbiIPwobJrwnFs8TrfWWro7HQVsrmPyJIxjgsu1oMGZYwacAsO47v+UuCBXYcu3JtjdRyub2+L65SNCh299eXDTxjPq0GkzZUHOHoj/lWYe/CCJgA="
    - secure: "CZ4RE0N0N/yeGnZZUf+ndN+vVzkLAgn2easCxExkOmvLqXmPNN9igKEaRAQ8sQ+YsAXuffyw2uxmo/paDUoVAcBpp/u/ZqdowdHHPcV13Upfqz70iQidsFU55zvF2CprmeHxNM1BLcbmVGY/tfeIrfosFSqb6gEOnSH/KfDsL6Y="
