language: java
jdk:
- oraclejdk8
addons:
  postgresql: 9.3
before_install:
- sh travis/before_install.sh
- export TERM=dumb
after_success:
- ./gradlew jacocoTestReport coveralls

sudo: false

cache:
  directories:
  - $HOME/.gradle/caches
